server:
  port: ${port:8080}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update